version: '2.3'

services:

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: ./gateway-service
    cpu_percent: 25
    mem_limit: 350m
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.25'
    #      memory: 300M
    environment: 
      JAVA_OPTIONS: "-Xmx100m"
    ports:
      - "8765:8765"
    networks:
      infra-nw:
      logs-nw:
      microservices-nw:
    depends_on:
      - discovery
      - zipkin
      - account-service
      - customer-service

  customer-service:
    image: customer-service
    container_name: customer-service
    build:
      context: ./customer-service
    cpu_percent: 25
    mem_limit: 350m
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.25'
    #      memory: 300M
    environment: 
      JAVA_OPTIONS: "-Xmx100m"
    ports:
      - "3333:3333"
    networks:
      infra-nw:
      logs-nw:
      microservices-nw:
    depends_on:
      #- logstash
      - log-queue
      - discovery
      - zipkin
      - account-service
  
  account-service:
    image: account-service
    container_name: account-service
    build:
      context: ./account-service
    cpu_percent: 25
    mem_limit: 350m
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.25'
    #      memory: 300M
    environment: 
      JAVA_OPTIONS: "-Xmx100m"
    ports:
      - "2222:2222"
    networks:
      infra-nw:
      logs-nw:
      microservices-nw:
    depends_on:
      #- logstash
      - log-queue
      - discovery
      - zipkin
  
  zipkin:
    image: zipkin
    container_name: zipkin
    build:
      context: ./zipkin-service
    cpu_percent: 25
    mem_limit: 250m
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.25'
    #      memory: 300M
    environment: 
      JAVA_OPTIONS: "-Xmx80m"
    ports:
      - "9411:9411"
    networks:
      logs-nw:
      infra-nw:
        aliases: 
          - zipkin-service
    depends_on:
      - discovery
      - elastic
  
  discovery:
    image: discovery
    container_name: discovery
    build:
      context: ./discovery-service
    cpu_percent: 25
    mem_limit: 300m
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.25'
    #      memory: 300M
    environment: 
      JAVA_OPTIONS: "-Xmx100m"
    ports:
      - "8761:8761"
    networks:
      infra-nw:
  
  log-queue:
    image: rabbitmq:3-management
    container_name: log-queue
    cpu_percent: 25
    mem_limit: 512m
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.25'
    #      memory: 521m
    #command: 
    #  - rabbitmq-server &
    #  - rabbitmqadmin declare queue name=q_logstash durable=true -u rabbit -p carrot &
    #  - rabbitmqadmin declare binding source=logs destination=q_logstash routing_key=microservices -u rabbit -p carrot
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "carrot"
    ports:
      - "5672:5672"
      - "5673:15672" # Management Console
    networks:
      logs-nw:
    #depends_on:
    #  - logstash
    
  
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    container_name: logstash
    cpu_percent: 25
    mem_limit: 512m
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.25'
    #      memory: 521m
    environment: 
      LS_JAVA_OPTS: "-Xms150m -Xmx150m"
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      logs-nw:
    depends_on:
      - elastic

  kibana:
    #image: docker.elastic.co/kibana/kibana-oss:6.2.2
    image: kibana:5.0
    container_name: kibana
    cpu_percent: 50
    mem_limit: 500m
    #environment: 
      #XPACK_SECURITY_ENABLED: "false"
    ports:
      - "5601:5601"
    networks:
      monitor-nw:
    depends_on:
      - elastic

  elastic:
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    image: elasticsearch:5.0
    container_name: elastic
    cpu_percent: 25
    mem_limit: 400m
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.25'
    #      memory: 400m
    environment:
      - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
      #- "cluster.name=dataprev"
      #- "transport.host=0.0.0.0"
    #volumes:
    # - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      logs-nw:
      monitor-nw:
        aliases:
          - elasticsearch # Necessário para que o serviço Kibana encontre o serviço do elastic
        
networks:
  infra-nw:
    name: infra-nw
  logs-nw:
    name: logs-nw
  monitor-nw:
    name: monitor-nw
  microservices-nw:
    name: microservices-nw
  
