server:  
  port: ${PORT:9411}

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka/
    registryFetchIntervalSeconds: 5
    
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: elastic:9200
      #cluster: elasticsearch
      index: zipkin
      index-shards: 5
      index-replicas: 1